### ISSUE TITLE
Better landing page

### ISSUE THREAD

**Issue by ykl7** [jhu-oose/www.jhu-oose.com#2]
Do you have any ideas for a landing page? If you have any particular direction you want to go with it, I can look at ideas along the same lines. @leafac

**Comment by leafac** [comment]
I think the landing page should have:

1. The links it currently has, and many more, for example, to lecture notes.
2. A short text describing what OOSE is. It must mention that OOSE is a course taught at JHU.
3. A short introductory video. I think it’s important that people get to see my face. Below is a script I wrote for such video a few months ago. I think that recording this can come later, after we finish TODOOSE.

* * *

Meet Jane. Jane learned how to program in college. She took courses in programming and data structures, but most of the programs she wrote were for homework. They were relatively short programs, and she never had to look at them again once the homework was submitted. Jane knows how to navigate the command line, trace down problems in her programs, and how to look for help online. But she doesn’t always understand the principles behind what she’s doing; she feels that sometimes the documentations she finds online are written in jargon she doesn’t speak; and sometimes she has to spend hours to fix a problem that was supposed to be simple.

In OOSE, Jane will work on the biggest software project of her life. She’ll work on the same codebase for an entire semester, instead of throwing it out. She’ll build software that has to be understood, maintained, and evolved. She’ll work with a group, and she’ll for the first time use a workflow used by programmers in industry and open-source projects. She’ll learn new software systems and understand more of the underlying principles behind those tools. She’ll become more confident as a software engineer. She’ll have a project to show her future potential employers and improve her CV for looking for internships.

Meet Zooey. Zooey learned how to program with her mother when she’s only a child. She realized early that she wanted a career in Computer Science. She interned as a software developer twice in the summers. Zooey knows how to navigate big codebases of projects she found in industry. She contributed to open-source projects. She’s secure about her skills as a software developer, and she can learn new software systems on her own.

In OOSE, Zooey will play with new technologies in which she’s interested. She’ll help the other members of her group project, and learn how to better articulate complex Computer Science ideas in simple terms. She’ll refine her understanding of the trade-offs between different software engineering decisions, and critique designs. She’ll build a project to improve her CV, and she may even deploy that product to production, making it available to real users.

It doesn’t matter if you identify yourself more with Jane or with Zooey, in any case you’ll build your confidence as a software engineer in OOSE.

The course is half theory, half practice. On the theory side, we’ll have classes covering the client–server architecture, which is the most common for modern apps; the design principles behind software that is easy to maintain and evolve; the design patterns that you find most commonly in codebases in object-oriented programming languages; the development process used by teams in industry and open-source projects alike; and so forth. We’ll have individual written assignments on those topics.

On the practice side of OOSE, we’ll have laboratory sessions in which you’ll work on a semester-long project in groups of approximately five students. You’ll come up with your project ideas, and you’re free to work on whatever you like. You’ll meet with your group advisor to get feedback on your progress, talk about your ideas, and help you fix issues. The group advisor is a staff member who will work with your group throughout the semester. Throughout the semester we’ll have checkpoints in which you’ll show your progress and we’ll discuss how you should proceed. You’ll start by specifying what the software will do and how it should function, and by the end of the semester we’ll have a presentation in which you’ll show a complete working system.

The OOSE staff is looking forward to working with you this semester and helping you build the greatest software of your life.

**Comment by leafac** [comment]
Work on the homepage is happening. We’ll see if the video will be made or not…
